package infrastructure

import (
	"fmt"
	"strings"

	"github.com/sudeeshjohn/powerhmc-go/examples/ocp-upi-deployer/communication"
)

// netmaskToCIDR converts a dotted decimal netmask to CIDR notation
func netmaskToCIDR(netmask string) string {
	netmaskMap := map[string]string{
		"255.255.255.255": "32",
		"255.255.255.254": "31",
		"255.255.255.252": "30",
		"255.255.255.248": "29",
		"255.255.255.240": "28",
		"255.255.255.224": "27",
		"255.255.255.192": "26",
		"255.255.255.128": "25",
		"255.255.255.0":   "24",
		"255.255.254.0":   "23",
		"255.255.252.0":   "22",
		"255.255.248.0":   "21",
		"255.255.240.0":   "20",
		"255.255.224.0":   "19",
		"255.255.192.0":   "18",
		"255.255.128.0":   "17",
		"255.255.0.0":     "16",
		"255.254.0.0":     "15",
		"255.252.0.0":     "14",
		"255.248.0.0":     "13",
		"255.240.0.0":     "12",
		"255.224.0.0":     "11",
		"255.192.0.0":     "10",
		"255.128.0.0":     "9",
		"255.0.0.0":       "8",
	}

	if cidr, ok := netmaskMap[netmask]; ok {
		return cidr
	}

	return netmask
}

// ExtractCIDRPrefix extracts the prefix from a CIDR notation (e.g., "192.0.2.0/20" -> "20")
func ExtractCIDRPrefix(cidr string) string {
	parts := strings.Split(cidr, "/")
	if len(parts) != 2 {
		return ""
	}
	return parts[1]
}

// CidrToNetmask converts CIDR notation to netmask (e.g., "192.0.2.0/20" -> "255.255.240.0")
func CidrToNetmask(cidr string) string {
	parts := strings.Split(cidr, "/")
	if len(parts) != 2 {
		return ""
	}

	// Parse prefix length
	prefixLen := 0
	fmt.Sscanf(parts[1], "%d", &prefixLen)
	if prefixLen < 0 || prefixLen > 32 {
		return ""
	}

	// Convert prefix length to netmask
	mask := ^uint32(0) << (32 - prefixLen)
	return fmt.Sprintf("%d.%d.%d.%d",
		byte(mask>>24), byte(mask>>16), byte(mask>>8), byte(mask))
}

// NetworkManager handles network configuration for OpenShift clusters
type NetworkManager struct {
	sshClient *communication.SSHClient
	verbose   bool
}

// NewNetworkManager creates a new NetworkManager instance
func NewNetworkManager(sshClient *communication.SSHClient, verbose bool) *NetworkManager {
	return &NetworkManager{
		sshClient: sshClient,
		verbose:   verbose,
	}
}

// AddVIPAlias adds a persistent VIP (Virtual IP) alias to a network interface
// The VIP configuration survives system reboots using ifcfg files
func (nm *NetworkManager) AddVIPAlias(iface, ip, netmask, clusterName string) error {
	if nm.verbose {
		fmt.Printf("[Network] Adding persistent VIP: %s to %s for cluster %s\n", ip, iface, clusterName)
	}

	cidr := netmaskToCIDR(netmask)

	// Create alias device name (e.g., ens3:0, ens3:1)
	// Use numeric suffix for better compatibility
	aliasDevice := fmt.Sprintf("%s:0", iface)

	// Step 1: Create persistent ifcfg file first (survives reboots)
	ifcfgContent := fmt.Sprintf(`# Persistent VIP configuration for OpenShift cluster: %s
# Generated by ocp-upi-deployer
# This configuration ensures the VIP survives system reboots
DEVICE=%s
BOOTPROTO=static
IPADDR=%s
NETMASK=%s
ONBOOT=yes
NM_CONTROLLED=no
`, clusterName, aliasDevice, ip, netmask)

	ifcfgPath := fmt.Sprintf("/etc/sysconfig/network-scripts/ifcfg-%s", aliasDevice)

	if nm.verbose {
		fmt.Printf("[Network] Creating persistent config: %s\n", ifcfgPath)
	}

	if err := nm.sshClient.UploadContent(ifcfgContent, ifcfgPath); err != nil {
		return fmt.Errorf("failed to create persistent ifcfg file: %v", err)
	}

	// Step 2: Activate the persistent configuration using ifup
	ifupCmd := fmt.Sprintf("sudo ifup %s", aliasDevice)
	if _, err := nm.sshClient.ExecuteCommand(ifupCmd); err != nil {
		if nm.verbose {
			fmt.Printf("[Network] ifup failed, trying manual IP add: %v\n", err)
		}

		// Fall back to manual IP add if ifup fails
		cmd := fmt.Sprintf("sudo ip addr add %s/%s dev %s", ip, cidr, iface)
		if _, err := nm.sshClient.ExecuteCommand(cmd); err != nil {
			// Ignore error if address already exists
			if !strings.Contains(err.Error(), "File exists") {
				return fmt.Errorf("failed to add IP alias: %v", err)
			}
			if nm.verbose {
				fmt.Printf("[Network] VIP already exists on interface\n")
			}
		}
	}

	if nm.verbose {
		fmt.Printf("[Network] ✅ VIP configured and persisted to %s\n", ifcfgPath)
	}

	return nil
}

// RemoveVIPAlias removes a VIP alias from a network interface and deletes persistent configuration
func (nm *NetworkManager) RemoveVIPAlias(iface, ip, netmask, clusterName string) error {
	if nm.verbose {
		fmt.Printf("[Network] Removing VIP: %s from %s for cluster %s\n", ip, iface, clusterName)
	}

	cidr := netmaskToCIDR(netmask)
	aliasDevice := fmt.Sprintf("%s:0", iface)

	// Step 1: Bring down the interface alias
	ifdownCmd := fmt.Sprintf("sudo ifdown %s", aliasDevice)
	if _, err := nm.sshClient.ExecuteCommand(ifdownCmd); err != nil {
		if nm.verbose {
			fmt.Printf("[Network] ifdown failed (interface may not be up): %v\n", err)
		}
	}

	// Step 2: Remove IP from interface (immediate)
	cmd := fmt.Sprintf("sudo ip addr del %s/%s dev %s", ip, cidr, iface)
	if _, err := nm.sshClient.ExecuteCommand(cmd); err != nil {
		if !strings.Contains(err.Error(), "Cannot assign requested address") {
			if nm.verbose {
				fmt.Printf("[Network] Warning: Failed to remove VIP from interface: %v\n", err)
			}
		}
	}

	// Step 3: Remove persistent ifcfg file
	ifcfgPath := fmt.Sprintf("/etc/sysconfig/network-scripts/ifcfg-%s", aliasDevice)
	if err := nm.sshClient.RemoveFile(ifcfgPath); err != nil {
		if nm.verbose {
			fmt.Printf("[Network] Warning: Failed to remove ifcfg file: %v\n", err)
		}
	} else {
		if nm.verbose {
			fmt.Printf("[Network] ✅ Removed persistent config: %s\n", ifcfgPath)
		}
	}

	return nil
}

// CheckVIPExists checks if a VIP is already configured on an interface
func (nm *NetworkManager) CheckVIPExists(iface, ip string) (bool, error) {
	checkCmd := fmt.Sprintf("sudo ip addr show dev %s | grep -q '%s/'", iface, ip)
	_, err := nm.sshClient.ExecuteCommand(checkCmd)
	if err != nil {
		// grep returns non-zero if not found
		return false, nil
	}
	return true, nil
}

// VerifyVIPPersistence verifies that the VIP configuration file exists and is valid
func (nm *NetworkManager) VerifyVIPPersistence(iface, clusterName string) (bool, error) {
	aliasDevice := fmt.Sprintf("%s:0", iface)
	ifcfgPath := fmt.Sprintf("/etc/sysconfig/network-scripts/ifcfg-%s", aliasDevice)

	checkCmd := fmt.Sprintf("test -f %s && echo 'exists'", ifcfgPath)
	output, err := nm.sshClient.ExecuteCommand(checkCmd)
	if err != nil {
		return false, nil
	}

	return strings.Contains(output, "exists"), nil
}

// Made with Bob
